### ISSUE TITLE
Nexus is not deployed but used in mlbparks lab

### ISSUE THREAD

**Issue by jbrannst** [osevg/workshopper-content#107]
I was running the Python version of the workshop.

If the user chooses to deploy mlbparks using
`oc new-app mlbparks --name=mlbparks -p MAVEN_MIRROR_URL=http://nexus.nationalparks-lab.svc.cluster.local:8081/repository/maven-all-public`
then the build will fail.
I deployed https://github.com/OpenShiftDemos/nexus/blob/master/nexus2-template.yaml into the lab namespace but that one uses /content/groups/public so it fails as well. It seems nexus3 will deploy the content where expected.

Maybe deploying a nexus3 can be an optional parameter?

**Comment by jbrannst** [comment]
I see that nexus3 is part of the APB so the cause must then have been a failed deployment. Not sure how to troubleshoot though.

**Comment by jbrannst** [comment]
Seems this issue and the other I filed on the devops workshop may be related to flaky redhat.registry.io access

**Comment by jbrannst** [comment]
Double check with RHPDS team confirms it is an issue with redhat.registry.io auth. A service account with credentials is required to be installed into each project. To avoid this manual work, we could update the APB to install a provided SA.

**Comment by alberttwong** [comment]
related to https://github.com/openshift-labs/starter-guides/issues/113 ???
