### ISSUE TITLE
Trying to install starter workshop on my own OCP environment

### ISSUE THREAD

**Issue by alberttwong** [osevg/workshopper-content#109]
Does someone have the steps to load the template / apb into my own OCP environment?

**Comment by alberttwong** [comment]
Is this it?
```
oc login
oc new-project lab-infra
oc run apb --restart=Never --image="openshiftapb/starter-workshop-apb:ocp-3.11" \
    -- provision -vvv -e namespace=$(oc project -q) -e openshift_token=$(oc whoami -t)
```

**Comment by alberttwong** [comment]
https://github.com/openshift-labs/starter-guides/pull/110

**Comment by alberttwong** [comment]
Found out that the only real way to provisioning the workshop is through adding the APB to your service catalog and going through the wizard.   If you use the above "oc run apb" it doesn't allow you to provision the number of users or type or any of the options you see in the wizard.

**Comment by alberttwong** [comment]
So the workshop seems to be deployed however I can't login with "user1" or any of the "user*.   Any ideas?

**Comment by alberttwong** [comment]
I'm  using htpasswd if it helps.

**Comment by alberttwong** [comment]
Checked the htpasswd file and the users were not created.   I manually created them.

**Comment by jorgemoralespou** [comment]
@alberttwong We target RHPDS clusters where the users have been already provisioned in the htpasswd. Yes, the APB should try to create them, but given that users might be identified in multiple ways, we can not target any, so the only thing we could do is either error out or provide a message.

Also, to run the APB you can do it from your local laptop, or from within the platform as a regular pod, but you're missing many required arguments. Look into this file: https://github.com/openshift-labs/starter-guides/blob/ocp-3.11/apb/provision

**Comment by alberttwong** [comment]
@jorgemoralespou Anything else I need to do other than create new users for the workshop?

**Comment by jorgemoralespou** [comment]
@alberttwong As long as your cluster is OCP and aligned with the version, no. 

If you want to use persistence, you need to make sure to have File Storage PVs available (else, select the ephemeral templates) although the APB does not yet allow you to select these.

**Comment by alberttwong** [comment]
Okay... hmm... do you have any instructions for the file storage PVs?

The reason why I ask is that one of my customers would like to run the starter workshop on their installation of OCP.

**Comment by jorgemoralespou** [comment]
Storage is used for databases, so any storage should work, unless you want to rolling deploy the databases (which you will probably not), in which case you'll need RWX, instead of just any storage.
