### ISSUE TITLE
Resource limit

### ISSUE THREAD

**Issue by bentterp** [osevg/workshopper-content#125]
I suggest applying some form of quota on the lab projects, to prevent lab users experimenting too freely with the replicationcount, as this can cause great disruption during the lab session.

**Comment by jbrannst** [comment]
A user quota draft is available but not implemented [1]. @jorgemoralespou can we please apply this or *something* like this to prevent users starting 2000 pods and killing the environment? The OpenShift Starter workshop is our most used workshop as it's great for onboarding basic-level users, which are the majority in most enterprise accounts.

[1] https://github.com/openshift-labs/starter-guides/edit/ocp-3.11/apb/roles/provision-java-starter-guides/tasks/per_user.yml

**Comment by jorgemoralespou** [comment]
on RHPDS clusters, which are the base target for this workshops a quota should exist, but yes, definitely we should look into at least limiting the number of pods, just in case.

I'll add it soon.

**Comment by jorgemoralespou** [comment]
Fixed by: https://github.com/openshift-labs/starter-guides/commit/efb4659a77e342cfdff6c247401e2c24dafc1556

If you feel more resources need to be quotad, just comment here.

**Comment by jbrannst** [comment]
Thanks! Will do nicely
