### ISSUE TITLE
Update oc client to at least 1.4

### ISSUE THREAD

**Issue by kenthua** [osevg/workshopper-content#13]
The oc client referenced in the lab is v1.3, which is sufficient for the current lab materials, but ideally want to at least match it up with the current OCP 3.4 runtime?

https://github.com/openshift/origin/releases/tag/v1.4.1

**Comment by jorgemoralespou** [comment]
Already merged by #42.

It supports 1.3, 1.4 and 1.5 using ocp and origin.
