### ISSUE TITLE
The .config directory should not be checked into Git repsitory.

### ISSUE THREAD

**Issue by GrahamDumpleton** [osevg/workshopper-content#147]
@jankleinert @jorgemoralespou 

Not sure how you managed to get it in there in `ocp-4.2` branch, but the `.config` directory should not be checked into the Git repository. Can only think maybe `workshop-dashboard` image was run locally with working directory mounted and so that directory from running container was written back and then accidentally added to Git repository.

**Comment by jorgemoralespou** [comment]
My fault. I did run it locally with mounted sources.
