### ISSUE TITLE
Nexus fails to deploy with latest image

### ISSUE THREAD

**Issue by therevoman** [osevg/workshopper-content#155]
Trying to provision this on an OpenShift 4.3 cluster and it appears the config file is different in the latest version of the nexus image.  

registry.connect.redhat.com/sonatype/nexus-repository-manager:3.21.1-01-ubi-2

**Comment by therevoman** [comment]
I'm sure there's a better way, but modifying `roles/ocp4-workload-nexus-operator/defaults/main.yml` ad changing the nexus image tag from `latest` to `3.19.1-01-ubi-1` lets the "Get Admin Password" task complete.

`_nexus_image_tag: 3.19.1-01-ubi-1`

**Comment by jankleinert** [comment]
@therevoman This should be resolved now if you are deploying from RHPDS (and cluster logging is properly enabled now, too). Let me know if you still encounter the issue.
