### ISSUE TITLE
Images in documentation fail to load

### ISSUE THREAD

**Issue by ottok** [osevg/workshopper-content#156]
Many images failed to load while I was reading the docs.

Example: https://github.com/openshift-labs/starter-guides/blob/ocp-3.11/nationalparks-python.adoc

![image](https://user-images.githubusercontent.com/668724/77016484-6b96d980-6980-11ea-9443-ba245355cac1.png)

**Comment by ottok** [comment]
Why did you close this without any comments?

**Comment by ottok** [comment]
Images at https://github.com/openshift-labs/starter-guides/blob/ocp-3.11/nationalparks-python.adoc are still broken. Shall I or the next person that encounters this bug just open a new issue?

**Comment by blues-man** [comment]
Hey Otto, sorry it was a bulk action on 3.x issues. Can you verify please if this bug still persists on 4.x ? Are you using this lab on OCP 3 from somewhere else than RHPDS?

**Comment by blues-man** [comment]
We are not maintaining it anymore for version 3, but if you managed to have it running and find it still useful, can you upload the correct screenshot for that?

**Comment by ottok** [comment]
I opened the link above for latest 4.5 and there the images load: https://github.com/openshift-labs/starter-guides/blob/ocp-4.5/workshop/content/nationalparks-python.adoc

So closing issue.

**Comment by blues-man** [comment]
Thanks :)
