### ISSUE TITLE
National  Park Deployment Step issue 

### ISSUE THREAD

**Issue by tosin2013** [osevg/workshopper-content#159]
National Parks Deployment step does not mention Java Version. The default version should be jdk8. 

Error found in https://github.com/openshift-labs/starter-guides/tree/ocp-4.2 branch.

**Comment by blues-man** [comment]
Thanks @tosin2013, I'm updating it for `ocp-4.4` branch and will mention JDK 11

**Comment by blues-man** [comment]
New version for `ocp-4.5` branch is Java 11
