### ISSUE TITLE
Original repositories for nationalparks

### ISSUE THREAD

**Issue by sobkowiak** [osevg/workshopper-content#167]
Hi. I have a question. Where can I find the original source repositories for the applications used in this workshop? E.g. for `nationalparks`. The content of the labs assumes the code is stored in Gogs deployed on the cluster, but I cannot find where are the sources from.

**Comment by blues-man** [comment]
Hi @sobkowiak, you can find all the repositories here:

- **Java**: https://github.com/openshift-roadshow/nationalparks.git
- **NodeJS**: https://github.com/openshift-roadshow//nationalparks-js.git
- **Python**:  https://github.com/openshift-roadshow//nationalparks-py.git
- **PHP**:  https://github.com/openshift-roadshow//nationalparks-php.git

I'm updating some of those for the new version of the lab :)

**Comment by sobkowiak** [comment]
Thanks @blues-man for the info :)
