### ISSUE TITLE
Update workshop to 4.6

### ISSUE THREAD

**Issue by blues-man** [osevg/workshopper-content#183]
* Update screenshots
* Check if all templates/dependencies are present
* Drop PHP and add .NET support

**Comment by ryanj** [comment]
TODO:

- [x] Cut a new `ocp-4.6` branch
- [x] update tags and strings in `.workshop/settings.sh`
- [x] update quay.io build triggers: https://quay.io/repository/openshiftlabs/lab-getting-started?tab=builds
- [x] deploy and test
- [x] MongoDB app updates...
- [x] create new agnosticd task, tags
- [x] Tekton Updates on AgnosticV and code
- [x] Move from DeploymentConfig to Deployment
- [x] Add .NET Lab

**Comment by blues-man** [comment]
The Dev catalog from RHPDS is pointing to my fork, after we test everything is fine we can send a PR for merging it into the Prod catalog:
https://github.com/blues-man/agnosticd/blob/development/ansible/roles/ocp4-workload-homeroomlab-starter-guides/defaults/main.yml#L13

**Comment by blues-man** [comment]
@ryanj I started updating all screenshots for 4.6 and using Deployment instead of DeploymentConfig, I added this point also to the TODO list

https://github.com/openshift-labs/starter-guides/commit/cac61ace33b0ee2c947946fcdf06c576611e834d

**Comment by blues-man** [comment]
Added the template for mongodb in this repo, so users can install it with `oc` as part o the lab inside their project:

https://github.com/openshift-labs/starter-guides/blob/ocp-4.6/mongodb-template.yaml

**Comment by blues-man** [comment]
@joellord is updating the frontend in order to have the map centered and zoomed on users' location when data point show up
https://github.com/openshift-roadshow/parksmap-web/issues/15

**Comment by blues-man** [comment]
@ryanj @joellord what do you think about adding a Pipeline from the embedded Pipeline UI when creating JS, Python, .NET backends from Topology view, and then adding Tekton Triggers instead of using BuildConfig Webhooks? In this way it would align to the Java workshop (which brings in addition a custom Pipeline for binary builds)

**Comment by blues-man** [comment]
Removing rollback and rollforward exercises due RS is pointing to the container image tag, while ImageStream hook injects the sha hash into Deployment, thus `oc rollout undo deployment/name` doesn't work since it points always to ImageStream tag and not the image sha hash

**Comment by blues-man** [comment]
https://github.com/redhat-cop/agnosticd/pull/3346
