### ISSUE TITLE
configmap on IE seems to have issues but not on chrome

### ISSUE THREAD

**Issue by alberttwong** [osevg/workshopper-content#19]
when saving properties files for configmap, IE seems to add a bunch of junk but same issue doesn't happen on chrome.  Should we suggest people use chrome (or maybe firefox)?

**Comment by thoraxe** [comment]
You mean when you use Internet Explorer to download the file to your local machine?

**Comment by alberttwong** [comment]
Yes.   Somehow IE downloads the file with hidden characters (tried to save as UTF8, ANSI) but still, you can tell the file isn't clean when you import the configmap (oc inspect it)
