### ISSUE TITLE
Python: Deploying the Database

### ISSUE THREAD

**Issue by benemon** [osevg/workshopper-content#191]
When deploying a database it says "Database Service Name : mongodb-nationalparks" However, the application is looking for a service called "mongodb". 

So either the application needs a config change to look for mongodb-nationalparks or the DB instructions should leave the database at the name "mongodb"

**Comment by blues-man** [comment]
The service name is `mongodb-nationalparks` as you can see here injected with env var `DATABASE_SERVICE_NAME` when deploying the app:
https://github.com/openshift-roadshow/nationalparks-py/blob/master/wsgi.py#L23

Maybe that is not clear from instructions?

**Comment by benemon** [comment]
Sorry if I wasn't clear - the delegate was saying that the Python app itself is looking for a Service called `mongodb`, not `mongodb-nationalparks`.

**Comment by blues-man** [comment]
Can you please point me to the source code when the delegate is saying that?

**Comment by benemon** [comment]
I'm running the workshop again today, so I'll double check if someone runs through the Python content.

**Comment by blues-man** [comment]
Fixed here https://github.com/openshift-roadshow/nationalparks-py/commit/7db30d82091a4042acf1aded40de2d342eb47c40
