### ISSUE TITLE
When doing jenkins module, attendees were confused on gateway errors

### ISSUE THREAD

**Issue by alberttwong** [osevg/workshopper-content#21]
maybe we need a page/container that tell them if something is truly broken or no active container is available.

**Comment by thoraxe** [comment]
"gateway errors"?

**Comment by alberttwong** [comment]
Yes.... 502 Bad Gateway error webpage shows up.  Just do a jenkins build and go the website before the deployment is completed.  I think this shows up because a deployment is in progress and there is no active pod to re-route traffic.
